---
Name: elements-global
After:
  - 'elements/*'
---
Arillo\Elements\ElementBase:
  extensions:
    - Arillo\ElementsGlobal\ElementGlobalExtension

Arillo\ElementsGlobal\ElementsGlobalModelAdmin:
  extensions:
    - Arillo\ElementsGlobal\ElementsGlobalModelAdminExtension